---
apiVersion: v1
kind: Service
metadata:
  name: account-summary
  labels:
    app: office-space
spec:
  type: ClusterIP 
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: office-space
    tier: summary
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: account-summary
  labels:
    app: office-space
spec:
  selector:
    matchLabels:
      app: office-space
      tier: transaction
  template:
    metadata:
      labels:
        app: office-space
        tier: transaction
    spec:
      containers:
        - image: gouthamve/account-summary:v29 
          imagePullPolicy: Always
          name: account-summary
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: password
            - name: MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: host
            - name: MYSQL_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: port
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.otel-collector.svc.cluster.local.:4317
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 80
              name: web
        - image: ubuntu
          imagePullPolicy: Always
          name: load-gen
          command: ["/bin/bash"]
          args: ["-c",  "apt-get -y update ; apt-get -y install curl; while sleep 1; do curl http://localhost; done"]
