---
apiVersion: v1
kind: Service
metadata:
  name: send-notification
  labels:
    app: office-space
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: office-space
    tier: notification
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: send-notification
  labels:
    app: office-space
spec:
  selector:
    matchLabels:
      app: office-space
      tier: notification
  template:
    metadata:
      labels:
        app: office-space
        tier: notification
    spec:
      containers:
        - image: gouthamve/java-application-send-notification:v18 
          imagePullPolicy: Always
          name: send-notification
          env:
            - name: GMAIL_SENDER_USER
              value: 'username@gmail.com'
            - name: GMAIL_SENDER_PASSWORD
              value: 'password@gmail.com'
            - name: EMAIL_RECEIVER
              value: 'sendTo@gmail.com'
            - name: OPENWHISK_API_URL_SLACK
              value: ''
            - name: SLACK_MESSAGE
              value: 'Your balance is over $50,000.00'
            - name: OPENWHISK_API_URL_EMAIL
              value: ''
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.otel-collector.svc.cluster.local.:4317
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
